### PR TITLE
Added check to make sure we arent calling a method that does not exist

### PR DESCRIPTION
**Pull request by shanahanjrs**
For some reason I would occasionally get `typeError: step.hasDataTable is not a function` so I added a check to make sure it exists before calling it.

### CODE REVIEW

**Comment by igniteram** [comment]
@shanahanjrs Yes even i have the same issue, thanks for submitting this PR.
@piociek @just-boris When can we expect these PR's to be merged?? any updates?

**Comment by just-boris** [comment]
Hello! I am not an expert in cucumber.js, but at first look at looks very weird, that sometimes API method are missed.

If @piociek will not answer in a next few days, I will try to sort this out.

**Comment by shanahanjrs** [comment]
@just-boris @igniteram  Not sure why the error was happening, this PR does not fix the issue, only checks that the method exists otherwise doesnt even try to call it, that way it finishes executing without error.

**Comment by piociek** [comment]
Hi, sorry for late response but I was busy with other stuff. 
Can you provide any steps to reproduce this problem that you try to solve with this PR? I haven't seen it so far, nor anyone using the plugin have reported it.

**Comment by piociek** [comment]
This should be fixed in 1.0.1.

If not please open new issue with example test that will allow reproduction of this problem

**Comment by shanahanjrs** [comment]
I haven't done a small project to reproduce it and the only code I have that was throwing the error is for work which I can't share publicly. I can just use my fork for now until its fixed.

**Comment by piociek** [comment]
Sure. I'm not asking for any confidential code. Please check new version of plugin and let me know if the problem still occurs.

Btw. what cucumber version are you using?

**Comment by shanahanjrs** [comment]
I'm using cucumber 1.0.0 from npm

**Comment by piociek** [comment]
Plugin version 1.0.1 will not work with cucumber 1.0.0. Please update cucumber to 1.2.0+

**Comment by just-boris** [comment]
@piociek you can specify compatible version in `peerDependencies` in package.json. Then guys will see a warning if case of mistmatch.

**Comment by piociek** [comment]
@just-boris splendid idea! peerDependency added in https://github.com/allure-framework/cucumberjs-allure-reporter/pull/8

**Pull request closed without merging**
